---
- name: "init images_to_download variable"
  set_fact:
    images_to_save: ""
  when:
    - not skip_downloads|default(false)

- name: "set images_to_download variable"
  set_fact:
    images_to_save: "{{ images_to_save }} {{ item.value.repo }}:{{ item.value.tag }}"
  with_dict: "{{ downloads }}"
  when:
  - not skip_downloads|default(false)

- name: "pull containers"
  shell: "docker pull {{ item.value.repo }}:{{ item.value.tag }}"
  with_dict: "{{ downloads }}"
  when:
  - not skip_downloads|default(false)

- name: "create cache directory"
  become: yes
  file:
    path: "{{ local_release_dir }}"
    state: directory
    recurse: yes
    mode: 0777
  when:
  - not skip_downloads|default(false)

- name: "save containers"
  shell: "docker save {{ images_to_save }} | xz -9 > {{ local_release_dir }}/{{ container_cache_name }}"
  when:
  - not skip_downloads|default(false)

- name: "copy kubectl with ver to static kubectl"
  copy:
    src: "{{ local_release_dir }}/kubectl-{{ kube_version }}-{{ image_arch }}"
    dest: "{{ local_release_dir }}/kubectl"
    mode: "preserve"
  when:
    - not skip_downloads|default(false)

- name: "patch calicoctl.sh with canal certs"
  replace:
    path: "{{ playbook_dir }}/roles/network_plugin/canal/templates/calicoctl.sh.j2"
    regexp: "calico_cert_dir"
    replace: "canal_cert_dir"
  when:
    - not skip_downloads|default(false)

- name: "copy cache to nodes"
  copy:
    src: "{{ release_cache_dir }}/"
    dest: "{{ local_release_dir }}"
  when:
  - skip_downloads|default(false)

- name: "load containers cache"
  shell: "docker load -i {{ local_release_dir }}/{{ container_cache_name }}"
  when:
  - skip_downloads|default(false)

- name: "copy calicoctl to nodes"
  copy:
    src: "{{ release_cache_dir }}/calicoctl"
    dest: "/usr/local/bin/calicoctl"
    mode: "0755"
  when:
  - skip_downloads|default(false)

